## Welcome to the Julia basics tutorial!

##### Write comments just as in python with the '#' symbol

##### Press [SHIFT] + [ENTER] to execute a cell

In [1]:
print("Hello world") # example of a comment

Hello world

Packages are central to any piece of Julia code (just as any language).
They allow us to use other people's work, specializing what we want our code to do.
Packages can either be from the standard library which comes with your Julia installation,
or they are installed from the internet.
To load a package, run the following line:

In [2]:
using LinearAlgebra, Pkg

These are two standard library packages, so you don't need to do any installations.
For the next package, we will need to download it from the internet.

In [3]:
Pkg.add("BenchmarkTools")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


In [23]:
# As we saw earlier, Julia is dynamically typed, which means we don't 
# have to specify a type for the variables we use.

a = 1
b = "two"
c = [3]
print(a, b, c)

1two[3]

This is purely aesthetic, but you can use any unicode character from <a href="https://docs.julialang.org/en/v1/manual/unicode-input/">https://docs.julialang.org/en/v1/manual/unicode-input/</a>.
To use these, type the common name such as 'alpha' after a backslash, and press [TAB] (`\alpha` + [TAB])

In [ ]:
α = "\alpha"
😎 = "\:sunglasses:"
ℵ = "\aleph"

In [ ]:
# You can also use this technique to do sub/super scripts. 
# To do this, type `\_1` or `\^2`. Note: you can't sub/super script anything

σ² = "\sigma [TAB] \^2 [TAB]"
Xₜ = "X [TAB] \_t [TAB]"
αᵅ = "\alpha [TAB] \^alpha [TAB]"

## Types
While you don't have to worry/care about types if you wish, it still help in understanding, potentially speeding up, and safe-guarding your code. You can use the function `typeof` to check the type of any variable. (```println``` below makes sure each is printed on a separate line)

In [10]:
println(typeof(a))
println(typeof(b))
println(typeof(c))

Int64
String
Vector{Int64}


In [24]:
# To check whether a variable is of a given type, you can use `isa`

println(a isa Int)
println(a isa Int64)

true
true


Wait, what just happened? `a` is both an `Int` and an `Int64`? What does that mean?

In Julia, there are two categories of types. Abstract types and Concrete types.
Concrete types are what you get from `typeof`, and they are the most specific description of your variable.
Abstract types are more general, and can be used to check broader categories.

For example, whether your variable is a `Float64` or an `Int64`, they are both numbers.
The type `Number` is an Abstract type that encompasses all numbers, for example:

In [15]:
println(1 isa Number)
println(-2.5 isa Number)
println(√π isa Number)

true
true
true


The most common primitive (most basic) types are:
- `Bool` (boolean, either true or false)
- `Int64` (64 bit integer, most numbers without decimal places are `Int64`)
- `Float64` (64 bit floating point number, most numbers with decimal places are `Float64`)
- `Char` (character, strings are made of these)
- `Symbol` (usually used for keyword arguments, will expand on later)

## BASIC OPERATORS 
(https://www.geeksforgeeks.org/operators-in-julia/)

In [25]:
# Here are the most common operators in Julia:

println(2 + 2)
println(4 - 3)
println(3 * 3)
println(8 / 2) #(returns float)
println(10 ÷ 3) #('\div' is integer division, it divides and ignores the decimal points)
println(10 \ 3) #(inverse division, only really useful when doing linear algebra)
println(2 ^ 3)
println(10 % 3) #(modulo operator, gives remainder after integer division)

4
1
9
4.0
3
0.3
8
1


In [26]:
# You can also change the value of a variable in place:

a = 2
a += 1 #(same as a = a + 1)
println(a)
b = 6
b *= 5 #(same as b = b * 5)
println(b)

3
30


In [27]:
# Here are the most common logical operators:

println(3 > 2)
println(2 <= 4)
println(4 == 4) #(checks if two values are the same)
println(4 != 4) #(checks if two values are different)
println((3 > 2) && (2 < 4)) #(logical and)
println((3 > 2) || (4 != 4)) #(logical or)
println(!(2 <= 4)) #(logical not)

true
true
true
false
true
true
false


## STRINGS

In [20]:
# Strings are useful if we want to print/display some text.

text = "This is a string"

"This is a string"

In [21]:
# If you want to incorporate a variable into your string, do the following:

text = "The value of a is: $(a)"

"The value of a is: 3"

In [28]:
# Adding two strings together can be done using the '*' operator

text = "A bit of text." * " And some more text"

"A bit of text.And some more text"

In [29]:
# Use \t to insert a tab, and \n to insert a line break

text = "Once upon a\ttime...\nOops"
println(text)

Once upon a	time...
Oops


In [30]:
# To go directly from numbers to strings:

text = string(2)
text isa String

true

In [31]:
# You can also go from text to numbers

numbers = parse(Int64, "10")
numbers isa Number

true

In [32]:
# You can split strings into arrays

split("This is a sentence.", " ")

4-element Vector{SubString{String}}:
 "This"
 "is"
 "a"
 "sentence."

In [33]:
# Or join an array into a string

join(["This", "is", "also", "a", "sentence."], "-")

"This-is-also-a-sentence."

## IF-ELSE

One of the most common tools in programming are the if-else statements.
In Julia, and `if` statement is always followed by an `end` (like in MATLAB)

In [35]:
if 10 > 4
    println("not surprising")
end 

a = 5
if a % 2 == 0
    println("a is even")
elseif a % 2 == 1
    println("a is odd")
else
    println("something went wrong...")
end

not surprising
a is odd


A very useful tool to compact things is the ternary operator which uses the question mark `?`.
The way this operator works is as follows: 
- You first provide a statement which could be true or false.
- Then you write the questoin mark, and then you write what follows if the statement is true.
- After this, you write a colon `:`, and then comes what has to happen is the statement is false.

In [36]:
a = 5
a % 2 == 0 ? print("a is even") : print("a is odd")

a is odd

In [37]:
# You can also chain these together

a = 5
a % 2 == 0 ? print("a is even") : a % 2 == 1 ? print("a is odd") : print("something went wrong...")

a is odd

## LOOPS

Another very common sight in programming are loops. These let you execute bits of code multiple times.

I will cover for loops, but not while loops, since I don't find them very useful (but they exist in Julia).

If we want to iterate over 10 numbers, we first create the range of numbers as in MATLAB using `1:10`

In [38]:
for i in 1:10
    print(i)
end

12345678910

In [41]:
# If we want to loop over every other number, we can use the following notation

for i in 1:2:10
    print(i)
end

13579

In [42]:
# We can also achieve this by using the 'continue' functionn

for i in 1:10
    if i % 2 == 0 # if i is even, skip and continue to next iteration
        continue
    end
    print(i)
end

13579

In [46]:
# If you want to break the loop early, because you achieve what you wanted, you can use the break function

for i in 1:100000
    if i ^ 2 > 100 # stop the loop after the square of i is bigger than 100
        break
    end
    print("$(i) ")
end

1 2 3 4 5 6 7 8 9 10 

In [49]:
# Similarly to the ternary operator '?', we can do loops in a single line (same as Python's list comprehension)
# Note that here, the results will go into an array (which we will cover next)

a = [i for i in 1:10]
println(a)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

## BASIC DATA STRUCTURES

We have previously discussed primitive types, but we can do more interesting stuff with them.
For example, once you have a number, you may be interested in forming a collection of numbers.

In Julia, there is a number of ways to store these numbers, the simplest of them being the array.

Like in MATLAB (and unlike Python), 1D arrays are vectors and 2D arrays are matrices.
Unline MATLAB (and like Python), it is very easy to add onto these arrays.

In [50]:
a = [5, 4, 3, 2, 1];
typeof(a)

Vector{Int64} (alias for Array{Int64, 1})

In [51]:
# We can find the length of the array with 'length'

length(a)

5

In [52]:
# The sum and product of elements in an array can be obtained with 'sum' and 'prod'

println(sum(a))
println(prod(a))

15
120


In [53]:
# To check whether the array is empty, use 'isempty'

isempty(a)

false

In [55]:
# Like with the range 1:10, we can loop over the contents of an array using 'in' (or ∈ = '\in')

for element in a
    print(element)
end

54321

In [57]:
# You can use 'in' (or '∉' '\notin') to check if an array contains (or does not contain) an item

println(2 ∈ a)
println(3 ∉ a)

true
false


In [60]:
# You can use the 'enumerate' function to keep track of the index as well as the value

for (index, element) in enumerate(a)
    println("$(index) - $(element)")
end

1 - 5
2 - 4
3 - 3
4 - 2
5 - 1


In [68]:
# To add onto an array, use the 'push!' function
# This function works in place, and so no assignment using '=' is needed.
# It adds the number to the end of the array. 

push!(a, 0)
println(a)

[5, 4, 3, 2, 1, 0]


In [64]:
# To remove the element at the end of the array, use 'pop!'

popped_number = pop!(a)
println(popped_number)
println(a)

0
[5, 4, 3, 2, 1]


In [67]:
# If you want to add/remove numbers to the front of the array, use 'pushfirst!' and 'popfirst!'

pushfirst!(a, 6)
println(a)
popped_number = popfirst!(a)

[6, 5, 4, 3, 2, 1]


6

In [69]:
# Like MATLAB (and unline Python), Julia uses 1 indexing. 
# (Mathematical consistency, Readability and clarity, Reduced potential for off-by-one errors)
# This means that to get the first element of an array you do:

a[1]

5

In [71]:
# And to get the last index, you do:

println(a[end])
println(a[end-1]) #(second to last index)

0
1


In [73]:
# To get the array in reverse order, use 'reverse':

reverse(a)
println(a)

[5, 4, 3, 2, 1, 0]


In [74]:
# EXTRA DETAIL
# This is not used very often, but to 'unpack' your array, you can use '...'

println(a...)

543210


In [76]:
# If you want to initialize a Vector, you can use the 'zeros' or 'ones' functions

println(zeros(5))
println(ones(5))

[0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 1.0, 1.0, 1.0]


In [81]:
# For higher order arrays, add more arguments
# (display shows the variable as it is, it's an alternative to println)

display(zeros(2, 2))
display(ones(5, 2))
println(ones(5, 2))

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

5×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

[1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0]


In [82]:
# For higher dimensional arrays, use 'size' instead of 'length':

a = zeros(10, 3)
size(a)

(10, 3)

In [83]:
# If you want to initialize a Vector as being empty, I recommend setting the type of the Vector as follows:

a = Vector{Int64}() #(this specifies what goes into your vector)
a = Int64[] #(this is an alternative way of doing it)
a = Vector{Vector{Int64}}() #(this is a vector of vectors, not a matrix!)
a = [] #(this is an empty vector with type 'Any' that goes in it, which means it can contain anything)

Any[]

In [84]:
# Use MATLAB notation to create matrices

A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [85]:
# You can use this to create block matrices too

B = [A A; A A]

4×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4

In [86]:
# You can also do this with vectors

a = [1, 2, 3]
A = [a a a]

3×3 Matrix{Int64}:
 1  1  1
 2  2  2
 3  3  3

In [88]:
# The 'hcat' and 'vcat' operators do the same thing:

display(hcat(a, a))
display(vcat(a, a))

3×2 Matrix{Int64}:
 1  1
 2  2
 3  3

6-element Vector{Int64}:
 1
 2
 3
 1
 2
 3

Arrays are mutable, which means that the data inside of them can be changed.
This is often useful, but leads to memory and speed inefficiencies.

The other way to store a series of number are tuples.
Tuples are immutable meaning their content cannot be changed.

In [92]:
a = (1, 2, 3)
println(typeof(a))
println(a[end])

Tuple{Int64, Int64, Int64}
3


The third basic data structure is the dictionary. This is implemented as a hash map. 

Dictionaries are useful if you want to index your data structure arbitrarily.

For example, to store the data for different subjects, you may want to use a dictionary since you can use the subject IDs to access the data.

In [123]:
# This is one way to add elements to the dictionary
data = Dict{String, Vector{Int}}("1A3CD" => [1, 4, 2, 4], "2HD7E" => [6, 4, 3, 8, 2])
data["F4JK3"] = [0, 4, 4, 5, 5] # This is another way
display(data)
println(data["1A3CD"])

Dict{String, Vector{Int64}} with 3 entries:
  "F4JK3" => [0, 4, 4, 5, 5]
  "2HD7E" => [6, 4, 3, 8, 2]
  "1A3CD" => [1, 4, 2, 4]

[1, 4, 2, 4]


In [95]:
# You can use the functions 'keys' and 'values' to access the set of keys and values of the dictionary.

println(keys(data))
println(values(data))

["F4JK3", "2HD7E", "1A3CD"]
[[0, 4, 4, 5, 5], [6, 4, 3, 8, 2], [1, 4, 2, 4]]


In [97]:
# This means we can loop over the data like so:

for subj in keys(data)
    print(length(data[subj])) # print length of data from each subject
end

554

In [100]:
# To convert these into arrays, we need to use the 'collect' function.

k = collect(keys(data))
v = collect(values(data))
println(typeof(k))
println(typeof(v))

Vector{String}
Vector{Vector{Int64}}


## FUNCTIONS

Julia is a funcional programming language. What that means is that everything is done through functions.
As we will see later, there are objects called `struct` that have some similarities to classes in python,
but Julia is not an object oriented programming language.

To define your own function, use the `function` keyword. Use `return` to indicate what the function should return when called

In [101]:
function sum_across_subjects(data)
    result = 0
    for subj in keys(data)
        result += sum(data[subj])
    end
    return result
end
sum_across_subjects(data)

52

In [102]:
# You can add optional arguments like so

function sum_across_subjects(data; exponent=1)
    result = 0
    for subj in keys(data)
        result += sum(data[subj])^exponent
    end
    return result
end
sum_across_subjects(data; exponent=2)

974

If you want to bullet-proof your code, assigning a type to the input and outputs of your function
makes sure that it takes in and spits out things in the correct format. 

We can assign a type to the inputs using the double colon notation `::` followed by the type

To assign a type to the output, use the double colon after the name of the function

In [104]:
function sum_across_subjects(data::Dict{String, Vector{Int}}; exponent::Int=1)::Int
    result = 0
    for subj in keys(data)
        result += sum(data[subj])^exponent
    end
    return result
end
sum_across_subjects(data; exponent="s") # incorrect inputs

TypeError: TypeError: in keyword argument exponent, expected Int64, got a value of type String

Commenting your code is always a good idea. For functions, there's an extra bit you can do to improve your code.

docstrings: explanations about how your function works, can be implemented using triple quotations `"""`

The format in Julia is the have the docstring right above your function, and as first line, have the name of the function with some inputs with four space before, followed by a one-line explanation of what the function does in present tense.


In [114]:
"""
    sum_across_subjects(data; exponent=1)

Sum data for each subject and raise to exponent.
"""
function sum_across_subjects(data::Dict{String, Vector{Int}}; exponent::Int=1)::Int
    result = 0
    for subj in keys(data)
        result += sum(data[subj])^exponent
    end
    return result
end

sum_across_subjects

One neat feature of Julia is that you can broadcast your function over arrays. What that means is that we can have a function (e.g. `sum`) and apply it to ever element of an array.

To do this, write a dot/period after the function and before the parentheses `sum.(array)`.

In [116]:
# Lets collect all the values of our data dict, 
# and broadcast the sum operator over it.

v = collect(values(data))
a = sum.(v)
sum(a) # this now returns the same as our sum_across_subjects function!

52

In [117]:
# The broadcast operator is also used to operate vectors element wise
# This code returns an error because it does not know how to multiply two row vectors together

a = [3, 2, 1]
b = [4, 5, 6]
a * b

MethodError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})

Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:587
  *(!Matched::Adjoint{<:Number, <:AbstractVector}, ::AbstractVector{<:Number})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.10.3/share/julia/stdlib/v1.10/LinearAlgebra/src/adjtrans.jl:462
  *(!Matched::Union{Adjoint{<:Any, <:StridedMatrix{T}}, Transpose{<:Any, <:StridedMatrix{T}}, StridedMatrix{T}}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF64, ComplexF32}, S<:Real}
   @ LinearAlgebra ~/.julia/juliaup/julia-1.10.3/share/julia/stdlib/v1.10/LinearAlgebra/src/matmul.jl:50
  ...


In [119]:
# The line below broadcasts the multiply operator over each element of the vector.

println(a .* b)

[12, 10, 6]


Some functions in Julia have an exclamation mark in them (like `push!` and `pop!` that we used earlier).
The exclamation mark is a convention in Julia to indicate that these functions work in place.
What this means is that these functions don't return anything: they modify their arguments.


In [122]:
# Here is an example below (note that the type of return is 'Nothing')

"""
    square_subject_data!(data)

Square data from each subject.
"""
function square_subject_data!(data::Dict{String, Vector{Int}})::Nothing
    for subj in keys(data)
        data[subj] = data[subj] .^ 2
    end
    return nothing
end
square_subject_data!(data)
display(data)
square_subject_data!(data)
display(data)

Dict{String, Vector{Int64}} with 3 entries:
  "F4JK3" => [0, 65536, 65536, 390625, 390625]
  "2HD7E" => [1679616, 65536, 6561, 16777216, 256]
  "1A3CD" => [1, 65536, 256, 65536]

Dict{String, Vector{Int64}} with 3 entries:
  "F4JK3" => [0, 4294967296, 4294967296, 152587890625, 152587890625]
  "2HD7E" => [2821109907456, 4294967296, 43046721, 281474976710656, 65536]
  "1A3CD" => [1, 4294967296, 65536, 4294967296]

In [125]:
# Similar to Python's lambda functions, Julia also has 'anynonymous functions' (aka one line functions)
# These functions use arrow notation. A simple example is shown below:

square = x -> x^2
println(square(2))
power_power = (x, y) -> 2^x^y
println(power_power(3, 3))

4
134217728


These anonymous functions can be useful in a number of cases. The most obvious is to find the position of an element in an array. 

This uses the `findfirst` or `findall` functions. These functions take a 'check' function as first argument to tell them what to look for.

This check is a statement that is applied to all elements, and those that satisfy it are returned

In [126]:
a = [0, 0, 1, 4, 3, 2, 4, 2]
check = x -> x == 2 # this checks whether 'x' is equal to 2 or not
println(findfirst(check, a)) # returns the index of the first element where check is satisfied
println(findall(check, a)) # returns all indices where check is satisfied

6
[6, 8]


In [127]:
# If we only want the values, but not the indices, we can use the broadcasting operator.
# For example, in the following array, imagine we only want the lists with length greater than 2.

a = [[1, 2, 3], [3, 3, 5, 6, 2], [2], [4, 2], [5, 2], [2], [2, 4, 6, 7]]

# We fist generate an array with a 1 if the element satisfied our demand, and 0 otherwise

b = length.(a) .> 2

# Then we can index our original array with this 'BitVector' to get the same result
a[b]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [3, 3, 5, 6, 2]
 [2, 4, 6, 7]

## STRUCTS

As I mentioned earlier, Julia is a functional programming language. 
If creating your own type (which you can do but we won't get into) is not enough, or you want a very custom data structure then structs may be useful. 

By default, structs are immutable, but they can be made mutable.

In [129]:
struct Car
    license_plate::String
    brand::String
    year_built::Int
    owners::Vector{String}
end

In [131]:
my_car = Car("1BC6TF", "Audi", 2017, ["Judy", "Bob"])
println(my_car.year_built)
pop!(my_car.owners)
println(my_car.owners)

2017
["Judy"]


In [132]:
my_car.license_plate = "1BC6TG"

ErrorException: setfield!: immutable struct of type Car cannot be changed

In [133]:
mutable struct MCar
    license_plate::String
    brand::String
    year_built::Int
    owners::Vector{String}
end
my_car = MCar("1BC6TF", "Audi", 2017, ["Judy", "Bob"])
my_car.license_plate = "1BC6TG"

"1BC6TG"

In [134]:
# You can view everything about a struct using 'dump'

dump(Car)
dump(my_car)

Car <: Any
  license_plate::String
  brand::String
  year_built::Int64
  owners::Vector{String}
MCar
  license_plate: String "1BC6TG"
  brand: String "Audi"
  year_built: Int64 2017
  owners: Array{String}((2,))
    1: String "Judy"
    2: String "Bob"
